// Draft content — review and edit before treating as final.
const PROJECTS = [
    {
        id: 'sreekamadhenu',
        type: 'client',
        name: 'Sree Kamadhenu',
        tagline: 'Sacred Flavors, Modern Soul',
        image: './assets/Sreekamadhenu_Visual.png',
        stack: ['Angular', 'Node.js', 'Express.js'],
        description: "A modern website for Sree Kamadhenu, a 28-year-old vegetarian restaurant chain, built around a QR-based ordering system; guests scan a code at their table, browse the branch's menu, and order straight from their phone.",
        about: "Sree Kamadhenu is a well-loved pure-vegetarian restaurant chain with seven branches and a story going back to 1997. The website carries that legacy online; sharing their story, signature dishes, and locations; while the QR ordering system lets guests browse and order right from the table, no waiting on a server. I built it in close collaboration with Claude, working through architecture and implementation decisions together.",
        contribution: 'Built the entire front-end in Angular, translating the brand\'s heritage identity into a responsive, animated interface (including the milestone counters and dish showcase), and contributed to parts of the back-end.',
        reason: 'Angular\'s component structure fit a multi-section marketing site with repeating UI patterns; dish cards, location cards, animated stat counters and kept the codebase organized as requirements grew.',
        challenge: 'The trickiest part was the POS integration; connecting the AWS-hosted app to the restaurant\'s local billing system. There were several ways to do it, and I needed one that was reliable without asking the client to run extra steps on their end.',
        solution: 'I researched the options with Claude and Perplexity to compare approaches and understand what was happening under the hood, then worked with Claude to implement the integration cleanly.',
        future: 'Next up: online payment integration, and an admin-assisted ordering option for customers who aren\'t comfortable using the QR system themselves.',
        funFact: 'My first real client project; the first time I built around someone else\'s brand, timeline, and feedback instead of my own.',
        links: {
            demo: 'https://sreekamadhenu.com',
        },
    },
    {
        id: 'projexpert',
        type: 'personal',
        name: 'ProjeXpert',
        tagline: 'Organize Smarter, Achieve Faster',
        image: './assets/projexpert_visual.png',
        stack: ['Angular', 'Express.js', 'MongoDB'],
        description: 'A scalable project management platform built to handle tasks, teams, and workflows efficiently, with real-time updates, structured task management, and seamless collaboration tools.',
        about: 'ProjeXpert is a scalable project management platform that keeps tasks, teams, and workflows organized in one place. It includes live chat and structured collaboration tools, built for teams juggling multiple projects at once.',
        contribution: 'Designed and built the full stack solo; the Angular front-end, the Express/MongoDB back-end, and the real-time layer connecting them.',
        reason: 'This was my first large-scale Angular project, and I chose it specifically to sharpen my Angular skills. Express and MongoDB kept the API flexible enough to handle task and team schemas as they evolved.',
        challenge: 'Being my first large Angular project, almost every feature came with its own learning curve, but the biggest challenge throughout was keeping data consistent across the app.',
        solution: 'I used RxJS Subjects and Angular Signals to manage shared state, keeping data consistent across every part of the app.',
        future: 'Next, I\'d like to bring in AI-assisted planning: a user simply describes what they\'re building, and AI checks team availability and task size to put together a suggested project plan.',
        funFact: 'This project is what pushed me to properly learn reactive state management (services, signals, and subjects) rather than just using them on the surface.',
        links: {
            demo: 'https://www.projexpert.xyz/',
            githubFrontend: 'https://github.com/Ajil-VC/projeXpert-frontend',
            githubBackend: 'https://github.com/Ajil-VC/projeXpert-backend',
        },
    },
    {
        id: 'shoeshope',
        type: 'personal',
        name: 'Shoeshope',
        tagline: 'Unbeatable Deals, Everyday Comfort',
        image: './assets/Shoeshope_Visual.png',
        stack: ['Express.js', 'EJS', 'MongoDB'],
        description: 'A modern e-commerce application for browsing and purchasing shoes with a seamless user experience. Includes product management, secure payments, and an intuitive shopping interface.',
        about: 'Shoeshope is a modern e-commerce application for browsing and purchasing shoes, covering the full flow from product discovery to secure checkout.',
        contribution: 'Built the entire application server-side with Express and EJS, including product management, the cart/checkout flow, and payment integration.',
        reason: 'A server-rendered EJS approach kept the e-commerce flow simple and fast to ship for a solo project, while MongoDB handled flexible product and catalog data well.',
        challenge: 'Handling secure, reliable payments and keeping product/inventory state consistent through the checkout flow.',
        solution: 'Integrated a payment gateway for checkout and used careful validation around stock levels to keep orders and inventory in sync.',
        future: 'Would like to add a wishlist feature and personalized recommendations based on browsing history.',
        funFact: 'First time implementing a real payment gateway end-to-end, from sandbox testing to going live.',
        links: {
            demo: 'https://shoeshope.projexpert.xyz/',
            github: 'https://github.com/Ajil-VC/ShoeShope-v2',
        },
    },
    {
        id: 'poll',
        type: 'personal',
        name: 'Poll',
        tagline: 'Ask. Vote. See Results Instantly.',
        image: './assets/Poll_visual.png',
        stack: ['Angular', 'Express.js', 'MongoDB'],
        description: 'A real-time polling platform that allows users to create, share, and vote on polls seamlessly. Features live result updates, efficient state management, and interactive UI components.',
        about: 'Poll is a real-time polling platform that lets users create, share, and vote on polls, with results updating live for everyone watching.',
        contribution: 'Built both the Angular front-end and the Express/MongoDB back-end, including the real-time results engine.',
        reason: 'Angular for a reactive, componentized UI, paired with Socket.io for instant result broadcasting without requiring users to refresh.',
        challenge: 'Keeping vote counts accurate and instantly synced across many simultaneous viewers without double-counting or race conditions.',
        solution: 'Used Socket.io for live broadcasting and atomic MongoDB update operations to keep vote counts accurate under concurrent votes.',
        future: 'Considering poll analytics (voting trends over time) and scheduled/timed polls.',
        funFact: 'The first project where I had to seriously think about race conditions and concurrent writes, not just UI logic.',
        links: {
            demo: 'https://poll-vert.vercel.app/',
            githubFrontend: 'https://github.com/Ajil-VC/Poll_Frontend',
            githubBackend: 'https://github.com/Ajil-VC/Poll_Backend',
        },
    },
];
