// Draft content — review and edit before treating as final.
const PROJECTS = [
    {
        id: 'sreekamadhenu',
        type: 'client',
        name: 'Sree Kamadhenu',
        tagline: 'Sacred Flavors, Modern Soul',
        image: './assets/Sreekamadhenu_Visual.png',
        stack: ['Angular', 'Node.js', 'Express.js'],
        description: 'A modern, elegant web presence for a 28-year-old vegetarian restaurant chain, built to bring a legacy family brand online.',
        about: 'Sree Kamadhenu is a well-established pure-vegetarian restaurant chain with seven branches and a story stretching back to 1997. The website introduces their story, signature dishes, and locations to a wider audience while keeping the warmth of their in-person hospitality intact.',
        contribution: 'Built the entire front-end in Angular, translating the brand\'s heritage identity into a responsive, animated interface (including the milestone counters and dish showcase), and contributed to parts of the back-end.',
        reason: 'Angular\'s component structure suited a multi-section marketing site with repeating UI patterns — dish cards, location cards, animated stat counters — while keeping the codebase organized as requirements evolved.',
        challenge: 'Translating a decades-old, heritage brand into a modern web experience without losing the warmth and trust it had built over 28 years of in-person hospitality.',
        solution: 'Leaned on real photography, restrained animation (scroll reveals, counting stats), and a typographic hierarchy that let the brand\'s own voice carry the design rather than imposing a generic restaurant-template look.',
        future: 'Natural next steps would be an online table reservation system and a digital ordering flow for individual branches.',
        funFact: 'This was my first real client project — the first time building around someone else\'s brand, timeline, and feedback instead of my own.',
        links: {
            demo: 'https://sreekamadhenu.com',
        },
    },
    {
        id: 'projexpert',
        type: 'personal',
        name: 'ProjeXpert',
        tagline: 'Organize Smarter, Achieve Faster',
        image: './assets/projexpert_visual.png',
        stack: ['Angular', 'Express.js', 'MongoDB'],
        description: 'A scalable project management system built to handle tasks, teams, and workflows efficiently. Features real-time updates, structured task management, and seamless collaboration tools.',
        about: 'ProjeXpert is a scalable project management system built to handle tasks, teams, and workflows efficiently, with real-time updates and structured collaboration tools for teams working across multiple projects.',
        contribution: 'Designed and built the full stack solo — the Angular front-end, the Express/MongoDB back-end, and the real-time layer connecting them.',
        reason: 'Angular with NgRx gave predictable state management for a data-heavy dashboard app, while Express and MongoDB kept the API flexible for evolving task and team schemas.',
        challenge: 'Keeping task and team state in sync in real time across multiple open sessions without the UI feeling laggy or inconsistent.',
        solution: 'Used WebSockets for live updates alongside a structured NgRx store, so every client reflects the same state without excessive polling.',
        future: 'Planned additions include Gantt-chart timelines and role-based permission tiers for larger teams.',
        funFact: 'This project pushed me to properly learn reactive state management (NgRx) instead of leaning on services and subjects alone.',
        links: {
            demo: 'https://www.projexpert.xyz/',
            githubFrontend: 'https://github.com/Ajil-VC/projeXpert-frontend',
            githubBackend: 'https://github.com/Ajil-VC/projeXpert-backend',
        },
    },
    {
        id: 'shoeshope',
        type: 'personal',
        name: 'Shoeshope',
        tagline: 'Unbeatable Deals, Everyday Comfort',
        image: './assets/Shoeshope_Visual.png',
        stack: ['Express.js', 'EJS', 'MongoDB'],
        description: 'A modern e-commerce application for browsing and purchasing shoes with a seamless user experience. Includes product management, secure payments, and an intuitive shopping interface.',
        about: 'Shoeshope is a modern e-commerce application for browsing and purchasing shoes, covering the full flow from product discovery to secure checkout.',
        contribution: 'Built the entire application server-side with Express and EJS, including product management, the cart/checkout flow, and payment integration.',
        reason: 'A server-rendered EJS approach kept the e-commerce flow simple and fast to ship for a solo project, while MongoDB handled flexible product and catalog data well.',
        challenge: 'Handling secure, reliable payments and keeping product/inventory state consistent through the checkout flow.',
        solution: 'Integrated a payment gateway for checkout and used careful validation around stock levels to keep orders and inventory in sync.',
        future: 'Would like to add a wishlist feature and personalized recommendations based on browsing history.',
        funFact: 'First time implementing a real payment gateway end-to-end, from sandbox testing to going live.',
        links: {
            demo: 'https://shoeshope.projexpert.xyz/',
            github: 'https://github.com/Ajil-VC/ShoeShope-v2',
        },
    },
    {
        id: 'poll',
        type: 'personal',
        name: 'Poll',
        tagline: 'Ask. Vote. See Results Instantly.',
        image: './assets/Poll_visual.png',
        stack: ['Angular', 'Express.js', 'MongoDB'],
        description: 'A real-time polling platform that allows users to create, share, and vote on polls seamlessly. Features live result updates, efficient state management, and interactive UI components.',
        about: 'Poll is a real-time polling platform that lets users create, share, and vote on polls, with results updating live for everyone watching.',
        contribution: 'Built both the Angular front-end and the Express/MongoDB back-end, including the real-time results engine.',
        reason: 'Angular for a reactive, componentized UI, paired with Socket.io for instant result broadcasting without requiring users to refresh.',
        challenge: 'Keeping vote counts accurate and instantly synced across many simultaneous viewers without double-counting or race conditions.',
        solution: 'Used Socket.io for live broadcasting and atomic MongoDB update operations to keep vote counts accurate under concurrent votes.',
        future: 'Considering poll analytics (voting trends over time) and scheduled/timed polls.',
        funFact: 'The first project where I had to seriously think about race conditions and concurrent writes, not just UI logic.',
        links: {
            demo: 'https://poll-vert.vercel.app/',
            githubFrontend: 'https://github.com/Ajil-VC/Poll_Frontend',
            githubBackend: 'https://github.com/Ajil-VC/Poll_Backend',
        },
    },
];
